
import javax.swing.UIManager;
import javax.swing.*;
import Cadastros.Gerenciador_Impressora;
import Cadastros.Gerenciador_ModeloImpressora;
import Cadastros.Gerenciador_Toners;
import Cadastros.Gerenciador_setor;
import Cadastros.Gerenciador_usuarios;
import Consulta.Emitir_Relatorios;
import acesso.GerenciadorAcesso;
import dao.ClienteDAO;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import utilitarios.ViewDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author thales
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private String seta_look = "javax.swing.plaf.nimbus.NimbusLookAndFeel";

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        lookandfeel();
        ClienteDAO.getInstance().findAll();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlData = new javax.swing.JLabel();
        jlHora = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        btConsulta = new javax.swing.JButton();
        btRelatorios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btToners = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        Menu_Cadastros = new javax.swing.JMenu();
        menuUsuario = new javax.swing.JMenuItem();
        menuImpressora = new javax.swing.JMenu();
        gerenciarImpressora = new javax.swing.JMenuItem();
        gerenciarModelo = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuSetor = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        Menu_sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Para Controle De Estoque");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(119, 172, 229));

        jlData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/data3.png"))); // NOI18N
        jlData.setText("Data.:");

        jlHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/if_Simple_clock_132151 (1).png"))); // NOI18N
        jlHora.setText("Hora:");

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair_dologin.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisar.png"))); // NOI18N
        btConsulta.setText("Consulta");

        btRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/impressora.png"))); // NOI18N
        btRelatorios.setText("Relatorios");
        btRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatoriosActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        jLabel3.setText("Usuario:");

        btToners.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/armario2.png"))); // NOI18N
        btToners.setText("Toners");
        btToners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTonersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlHora)
                .addGap(32, 32, 32)
                .addComponent(jlData)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btToners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlHora)
                    .addComponent(jlData))
                .addGap(12, 12, 12)
                .addComponent(btConsulta)
                .addGap(18, 18, 18)
                .addComponent(btRelatorios)
                .addGap(18, 18, 18)
                .addComponent(btToners)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSair, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        Menu_Cadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/group_add.png"))); // NOI18N
        Menu_Cadastros.setText("Gerenciar");

        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/group_add.png"))); // NOI18N
        menuUsuario.setText("Usuarios");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        Menu_Cadastros.add(menuUsuario);

        menuImpressora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/printer.png"))); // NOI18N
        menuImpressora.setText("Impressoras");

        gerenciarImpressora.setText("Impressoras");
        gerenciarImpressora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarImpressoraActionPerformed(evt);
            }
        });
        menuImpressora.add(gerenciarImpressora);

        gerenciarModelo.setText("Modelos");
        gerenciarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarModeloActionPerformed(evt);
            }
        });
        menuImpressora.add(gerenciarModelo);

        Menu_Cadastros.add(menuImpressora);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/help.png"))); // NOI18N
        jMenuItem3.setText("Fornecedor");
        Menu_Cadastros.add(jMenuItem3);

        menuSetor.setText("Setores");
        menuSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSetorActionPerformed(evt);
            }
        });
        Menu_Cadastros.add(menuSetor);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/door_out.png"))); // NOI18N
        jMenuItem9.setText("Sair");
        jMenuItem9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem9MouseClicked(evt);
            }
        });
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        Menu_Cadastros.add(jMenuItem9);

        jMenuBar2.add(Menu_Cadastros);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/wrench_orange.png"))); // NOI18N
        jMenu3.setText("Utilitarios");

        jMenuItem11.setText("Metal");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem13.setText("Motif");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem14.setText("Nimbus");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuBar2.add(jMenu3);

        Menu_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/door_out.png"))); // NOI18N
        Menu_sair.setText("Fechar");
        Menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_sairMouseClicked(evt);
            }
        });
        Menu_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_sairActionPerformed(evt);
            }
        });
        jMenuBar2.add(Menu_sair);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // TODO add your handling code here:
    }//GEN-LAST:event_timer1OnTime

    private void Menu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Menu_sairActionPerformed

    private void Menu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_sairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Menu_sairMouseClicked

    private void jMenuItem9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem9MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuItem9MouseClicked

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        seta_look = "javax.swing.plaf.nimbus.NimbusLookAndFeel";
        lookandfeel();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        seta_look = "javax.swing.plaf.metal.MetalLookAndFeel";
        lookandfeel();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        seta_look = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
        lookandfeel();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void menuSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSetorActionPerformed
        Gerenciador_setor form = new Gerenciador_setor();
        ViewDialog view = new ViewDialog("Gerenciador de Setor", form, new Dimension(550, 400), this);
        form.setView(view);
        view.showView();
    }//GEN-LAST:event_menuSetorActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        Gerenciador_usuarios form = new Gerenciador_usuarios();
        ViewDialog view = new ViewDialog("Gerenciador de Usuarios", form, new Dimension(450, 400), this);
        form.setView(view);
        view.showView();
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void gerenciarImpressoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarImpressoraActionPerformed
        Gerenciador_Impressora form = new Gerenciador_Impressora();
        ViewDialog view = new ViewDialog("Gerenciador de Impressoras", form, new Dimension(650, 450), this);
        form.setView(view);
        view.showView();
    }//GEN-LAST:event_gerenciarImpressoraActionPerformed

    private void gerenciarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarModeloActionPerformed
        Gerenciador_ModeloImpressora form = new Gerenciador_ModeloImpressora();
        ViewDialog view = new ViewDialog("Gerenciador de Impressoras", form, new Dimension(450, 400), this);
        form.setView(view);
        view.showView();
    }//GEN-LAST:event_gerenciarModeloActionPerformed

    private void btRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatoriosActionPerformed
        Emitir_Relatorios form = new Emitir_Relatorios();
        ViewDialog view = new ViewDialog("Emição de Relatorios", form, new Dimension(400, 190), this);
        form.setView(view);
        view.showView();
    }//GEN-LAST:event_btRelatoriosActionPerformed

    private void btTonersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTonersActionPerformed
        Gerenciador_Toners form = new Gerenciador_Toners();
        ViewDialog view = new ViewDialog("Gerenciador_Toners", form, new Dimension(650, 500), this);
        form.setView(view);
        view.showView();
    }//GEN-LAST:event_btTonersActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);

        ///Data
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jlData.setText(formato.format(dataSistema));

        //hora
        Timer timer = new Timer(1000, new hora());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                ClienteDAO.getInstance();

                GerenciadorAcesso.getInstance().login();

                JFrame tela = new TelaPrincipal();
                tela.setLocationRelativeTo(null);
                tela.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                tela.setVisible(true);
                System.out.println(".run() ");

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_Cadastros;
    private javax.swing.JMenu Menu_sair;
    private javax.swing.JButton btConsulta;
    private javax.swing.JButton btRelatorios;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btToners;
    private javax.swing.JMenuItem gerenciarImpressora;
    private javax.swing.JMenuItem gerenciarModelo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlHora;
    private javax.swing.JMenu menuImpressora;
    private javax.swing.JMenuItem menuSetor;
    private javax.swing.JMenuItem menuUsuario;
    // End of variables declaration//GEN-END:variables

    public void lookandfeel() {

        try {
            UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }

    
    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            jlHora.setText(String.format("%1$tH:%1tM", now));
        }
    }

}
